### PR TITLE
Fix missing username and email address in verification email

### PR DESCRIPTION
**Pull request by njatkinson**
* Explicitly pass through username & email address when rendering verification mail
* Fixes: https://github.com/TheCodeForge/syzitus/issues/12

### CODE REVIEW

**Comment by njatkinson** [comment]
It's been a while since I've used Flask, but I noticed that the elements that don't get rendered are using the Flask magic `g` variable, which I suspect is not accessible in the Jinja rendering context unless you pass it in. Rather than taking that approach, it seemed better to simply explicitly pass through just the variables we need.

**Comment by TheCodeForge** [comment]
Investigation result:

`g` is accessible inside Jinja but `g.user` isn't set until after you already have (and are signed into) an account. Which means that during signup, `g.user` is empty, and therefore so is the information in the email.

**Comment by TheCodeForge** [comment]
What's your syzitus name? So I can award you the code contributor badge?

**Comment by njatkinson** [comment]
Cool, thanks for investigating this and clarifying on available of `g`. Normally, I would set up a test environment and try this myself, but it looked like something easy enough to fix.

**Pull request merged**
